---
- name: Get todo.sh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/todotxt/todo.txt-cli/master/todo.sh
    dest: "{{ todo_sh_location }}"
    mode: "0744"

- name: Template the todo.sh fish file
  ansible.builtin.template:
    src: "todo.sh.fish.j2"
    dest: "{{ xdg_config_dir }}/fish/conf.d/todo.sh.fish"
    mode: "0744"

- name: Check if the config dir exists
  ansible.builtin.file:
    path: "{{ xdg_config_dir }}/todo.sh"
    state: directory
    mode: "0744"

- name: Template the todo.sh config file
  ansible.builtin.template:
    src: "config.j2"
    dest: "{{ xdg_config_dir }}/todo.sh/config"
    mode: "0744"

- name: Install the fish completions
  ansible.builtin.template:
    src: "todo.sh.completions.fish"
    dest: "{{ xdg_config_dir }}/fish/completions/todo.sh.fish"
    mode: "0744"
