theme = "onelight"

[editor]
mouse = true
# scrolloff = 999
bufferline = "always"
rulers = [80]
line-number = "relative"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[keys.normal.space.i]
b = ":insert-output printf \"\\x60\\x60\\x60\n\n\\x60\\x60\\x60\""

# Use C-c to quit everything
[keys.normal]
"C-c" = ["keep_primary_selection", "collapse_selection"]
# Until the next Helix version, need to keep this
# "C-/" = "toggle_comments"
"A-/" = "toggle_comments"

[keys.insert]
"C-c" = "normal_mode"
"A-/" = "toggle_comments"

[keys.select]
"C-c" = ["normal_mode", "keep_primary_selection", "collapse_selection"]
"A-/" = "toggle_comments"
