[[language]]
name = "markdown"
indent = { tab-width = 2, unit = "  "}

[[language]]
name = "latex"
scope = "source.tex"
injection-regex = "tex"
file-types = ["tex"]
roots = []
comment-token = "%"
language-server = { command = "texlab" }
config = { texlab.rootDirectory = "."}
indent = { tab-width = 4, unit = "\t" }