- name: Install the extensions
  ansible.builtin.command: "codium --install-extension {{ item }}"
  register: ext_install
  changed_when: '"already installed." not in ext_install.stdout'
  loop:
    - "eamodio.gitlens"
    - "ms-python.python"
    - "piousdeer.adwaita-theme"
    - "PKief.material-icon-theme"
    - "redhat.ansible"
    - "redhat.vscode-yaml"
