---
- name: Install python
  become: true
  ansible.builtin.dnf:
    name: python
    state: present

- name: Install pip
  become: true
  ansible.builtin.dnf:
    name: python3-pip
    state: present
