---
- name: Make sure that fonts directory exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.fonts"
    state: directory
    mode: "0755"

- name: Check whether this font is installed
  ansible.builtin.find:
    paths: "{{ fonts_dir }}"
    patterns:
      - "{{ font.glob }}"
  register: font_exists

- name: Download font
  when: font_exists.matched == 0
  ansible.builtin.unarchive:
    src: "{{ font.url }}"
    dest: "{{ fonts_dir }}"
    remote_src: true
