---
- name: Enable adw-gtk3-copr
  become: true
  community.general.copr:
    name: nickavem/adw-gtk3
    state: enabled

- name: Install adw-gtk3
  become: true
  ansible.builtin.dnf:
    name: adw-gtk3

- name: Install Firefox Gnome theme
  ansible.builtin.include_tasks:
    file: firefox_gnome_theme.yml

# Theming
- name: Set GTK theme and font
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: /org/gnome/desktop/interface/gtk-theme, value: "'adw-gtk3'" }
    - { key: /org/gnome/desktop/interface/cursor-theme, value: "'Adwaita'" }
    - { key: /org/gnome/desktop/interface/icon-theme, value: "'Adwaita'" }
    - { key: /org/gnome/desktop/interface/monospace-font-name, value: "'IosevkaTerm Nerd Font 12'" }
    - { key: /org/gnome/desktop/interface/font-name, value: "'Cantarell 11'" }
    - { key: /org/gnome/desktop/interface/document-font-name, value: "'Cantarell 11'" }
    - { key: /org/gnome/desktop/wm/preferences/theme, value: "'Adwaita'" }
    - { key: /org/gnome/desktop/wm/preferences/titlebar-font, value: "'Roboto Bold 12'" }
