---
# Workspaces
- name: Disable dynamic workspaces
  dconf:
    key: /org/gnome/mutter/dynamic-workspaces
    value: false

- name: Set number of workspaces to {{ workspaces|length }}
  dconf:
    key: /org/gnome/desktop/wm/preferences/num-workspaces
    value: "{{ workspaces|length }}"

- name: Disable old keybindings
  dconf:
    key: /org/gnome/shell/keybindings/switch-to-application-{{ item }}
    value: "['']"
  loop: "{{ workspaces }}"

- name: Set now Workspace keybindings
  dconf:
    key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-{{ item }}
    value: "['<Super>{{ item }}']"
  loop: "{{ workspaces }}"

- name: Set now Workspace keybindings for moving windows
  dconf:
    key: /org/gnome/desktop/wm/keybindings/move-to-workspace-{{ item }}
    value: "['<Super><Shift>{{ item }}']"
  loop: "{{ workspaces }}"

- name: Set center windows
  dconf:
    key: /org/gnome/mutter/center-new-windows
    value: true

- name: Set Workspaces on all screens
  dconf:
    key: /org/gnome/mutter/workspaces-only-on-primary
    value: false

# Keybindings
- name: Set keybindings
  dconf:
    key: /org/gnome/desktop/wm/keybindings/{{ item.command}}
    value: "{{ item.binding}}"
  loop:
    - { command: switch-applications, binding: "['<Super>Tab']" }
    - { command: switch-applications-backward, binding: "['<Shift><Super>Tab']" }
    - { command: switch-group, binding: "['<Alt>Tab']" }
    - { command: switch-group-backward, binding: "['<Shift><Alt>Tab']" }
    - { command: minimize, binding: "['']" }
    - { command: move-to-monitor-down, binding: "['<Shift><Super>j']" }
    - { command: move-to-monitor-up, binding: "['<Shift><Super>k']" }
    - { command: move-to-monitor-left, binding: "['<Shift><Super>h']" }
    - { command: move-to-monitor-right, binding: "['<Shift><Super>l']" }
    - { command: close, binding: "['<Shift><Super>q']" }

- name: Set keybindings in other places
  dconf:
    key: "{{ item.command }}"
    value: "{{ item.binding }}"
  loop:
    - { command: /org/gnome/settings-daemon/plugins/media-keys/screensaver, binding: "['<Ctrl><Super>l']" }
    - { command: /org/gnome/desktop/input-sources/xkb-options, binding: "['ctrl:nocaps', 'altwin:swap_lalt_lwin']" }
    - { command: /org/gnome/shell/keybindings/toggle-message-tray, binding: "['']" }

# Other Settings
- name: Set search provider settings
  dconf:
    key: /org/gnome/desktop/search-providers{{ item.key }}
    value: "{{ item.value }}"
  loop:
    - key: sort-order
      value: "['org.gnome.Nautilus.desktop', 'org.gnome.Documents.desktop', 'org.gnome.Settings.desktop', 'org.gnome.Software.desktop', 'org.gnome.Boxes.desktop',
        'org.gnome.Calculator.desktop', 'org.gnome.Calendar.desktop', 'org.gnome.Characters.desktop', 'firefox.desktop', 'org.gnome.clocks.desktop', 'org.gnome.Photos.desktop',
        'org.gnome.Contacts.desktop']"
    - { key: disabled, value: "['org.gnome.Contacts.desktop', 'org.gnome.Photos.desktop', 'org.gnome.clocks.desktop']" }
