- name: Check rust
  include_tasks: "{{ languages_dir }}/rust.yml"

- name: Get bartib
  ansible.builtin.git:
    repo: "{{ bartib_remote_repo }}"
    dest: "{{ bartib_source_dir }}"
    single_branch: yes
    version: master

- name: Check whether the fish completions directory exists
  ansible.builtin.file:
    path: "{{ xdg_config_dir }}/fish/completions"
    state: directory

- name: Install local bartib
  community.general.cargo:
    name: bartib
    path: "{{ bartib_source_dir }}"

- name: Link the bartib completions from there
  ansible.builtin.file:
    src: "{{ bartib_source_dir }}/misc/bartib.fish"
    dest: "{{ xdg_config_dir }}/fish/completions/bartib.fish"
    state: link
    force: yes

