---
- name: Configure custom copr for helix
  become: true
  community.general.copr:
    name: varlad/helix
    state: enabled

- name: Install helix
  become: true
  ansible.builtin.dnf:
    name:
      - helix
    state: latest

- name: Test whether {{ xdg_config_dir }}/helix dir exists
  stat:
    path: "{{ xdg_config_dir }}/helix"
  register: existing_dir

- name: Remove {{ xdg_config_dir }}/helix directory
  ansible.builtin.file:
    path: "{{ xdg_config_dir }}/helix"
    state: absent
  when: existing_dir.stat is defined and existing_dir.stat.islnk is false

- name: Link the helix configuration files
  ansible.builtin.file:
    src: "{{ wac_dir }}/roles/cli-tools/helix"
    dest: "{{ xdg_config_dir }}/helix"
    state: link
    force: true

- name: Install the wl-clipboard package from dnf
  become: true
  ansible.builtin.dnf:
    name: wl-clipboard
    state: latest
