- name: Get todo.sh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/todotxt/todo.txt-cli/master/todo.sh
    dest: "{{ todo_sh_location }}"

- name: Give the file executable permissions
  ansible.builtin.file:
    path: "{{ todo_sh_location }}/todo.sh"
    mode: +x

- name: Link the todo.sh fish file
  ansible.builtin.file:
    src: "{{ wac_dir }}/roles/cli-tools/todo.sh/todo.sh.fish"  
    dest: "{{ xdg_config_dir }}/fish/conf.d/todo.sh.fish"
    state: link
    force: yes

- name: "Check if {{ xdg_config_dir }}/todo.sh exists"
  ansible.builtin.file:
    path: "{{ xdg_config_dir }}/todo.sh"
    state: directory

- name: Template the todo.sh config file
  ansible.builtin.template:
    src: "{{ wac_dir }}/roles/cli-tools/todo.sh/config.j2"
    dest: "{{ xdg_config_dir }}/todo.sh/config"

- name: Check whether the fish completions directory exists
  ansible.builtin.file:
    path: "{{ xdg_config_dir }}/fish/completions"
    state: directory

- name: Link the fish completions
  ansible.builtin.file:
    src: "{{ wac_dir }}/roles/cli-tools/todo.sh/todo.sh.completions.fish"  
    dest: "{{ xdg_config_dir }}/fish/completions/todo.sh.fish"
    state: link
    force: yes


    