# 
- name: Enable the VSCodium Repository
  become: true
  yum_repository:
    name: gitlab.com_paulcarroty_vscodium_repo
    description: The VSCodium repository
    baseurl: https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/
    gpgkey: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    gpgcheck: 1
    enabled: 1
    repo_gpgcheck: 1
    metadata_expire: 1h

- name: Install VSCodium
  become: true
  ansible.builtin.dnf:
    name: 
      - codium
    state: present

- name: "Make sure that {{ xdg_config_dir }}/VSCodium/User directory exists"
  file:
    path: "{{ xdg_config_dir }}/VSCodium/User"
    state: directory

- name: Install the configuration files
  ansible.builtin.template:
    src: "{{ wac_dir }}/roles/apps/codium/{{ item }}.json.j2"
    dest: "{{ xdg_config_dir }}/VSCodium/User/{{ item }}.json"
  loop: 
    - "settings"
    - "keybindings"
