---
- name: Install latex dependencies
  become: true
  ansible.builtin.dnf:
    name:
      - texlive-scheme-medium
      - texlive-capt-of
      - texlive-abstract
      - texlive-hanging
      - texlive-biblatex-ieee
      - texlive-wrapfig
      - texlive-newunicodechar
      - texlive-todonotes
    state: latest

- name: Install texlab lang server
  tags:
    - lsp
    - never
  block:
    - name: Check cargo
      ansible.builtin.include_tasks:
        file: "{{ languages_dir }}/rust.yml"
    - name: Install texlab for LaTeX
      community.general.cargo:
        name: texlab
