---
- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: true
  changed_when: false

- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"
    force: "yes"

- name: install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust

- name: Install rust-analyzer
  become: true
  ansible.builtin.dnf:
    name: rust-analyzer
    state: latest
  tags:
    - lsp
    - never
